### ISSUE TITLE
RESULTS AND DATE!!!

### ISSUE THREAD

**Issue by MMAKENPO** [Zanneleen/expressItunesApp#1]
hello from Greece!!!happy and blessed new year for you and your family...my friend many congratulationsssssssssssss for this amazing web.greattttttttttt job!my friend I am searching for many months one web like yours!!!but please could you make it increase unlimited results?it would be great!!!I know itunes have limit but you as developer I am sure you can create one button load more !!!and pleaseeeeeeeee I am begging you can you make it appear also date for every song or year?!!!God bless you!!! unfortunately I have no idea from developing and programming!!!  pleaseeeeeeeeeeeee Zanneleen

**Comment by Zanneleen** [comment]
Halo I can not make the API show more results because that is the only results Apple API have. I would have to change the API you can try it however! :)
What date are you referring to?

**Comment by MMAKENPO** [comment]
zanneleen hello from Greece!!!nice to meet youuuuuuuuuuuu!!!!look I love spanish music so muchhhhhhhhhhhh especially pop,balada!!!please I am sure there is some way to increase unlimited results!!!one button load more for example....and date I mean one feature search by year or date...its up to you!!!I AM BEGGING YOUUUUUUUUUU....

**Comment by MMAKENPO** [comment]
I AM NOT PROGRAMMER,DEVELOPMENT...I HAVE NO IDEA....PLEASE ZANNELEEN....

**Comment by MMAKENPO** [comment]
please my friend can you?

**Comment by Zanneleen** [comment]
Halo as I said there isn't a way to increase results. At the moment I'm busy with a few projects so maybe in the future I will add it, but not now.

**Comment by MMAKENPO** [comment]
oooo ok....as you wish...and please I am sorry if I am disturb you!!!take care
